### ISSUE TITLE
How to reinstantiate previously created sessions?

### ISSUE THREAD

**Issue by Terf** [dgruber/drmaa2os#24]
If I start a job then my script dies, is there any way to reinstantiate the previously created session manager (as it appears to be serialized in the sqlite database?), or if I must create a new session manager, can I create a new job object with the ID of a running job started through DRMAA so I can call methods like GetState()?

**Comment by dgruber** [comment]
Which backend are you using? If jobs are available after an application restart certainly depends on the backend. Yes, the DB is intended for making job sessions persistent. For Kubernetes you can get the job back as long as it is available in Kubernetes, also after a restart of your application / script.

If you run following app twice it lists your previous job:

```
package main

import (
	"fmt"

	"github.com/dgruber/drmaa2interface"
	"github.com/dgruber/drmaa2os"

	_ "github.com/dgruber/drmaa2os/pkg/jobtracker/kubernetestracker"
)

func main() {

	sm, err := drmaa2os.NewKubernetesSessionManager(nil, "testdb.db")
	if err != nil {
		panic(err)
	}

	js, err := sm.CreateJobSession("jobsession1", "")
	if err != nil {
		js, err = sm.OpenJobSession("jobsession1")
		if err != nil {
			panic(err)
		}
	}
	defer js.Close()

	filter := drmaa2interface.CreateJobInfo()
	existingJobs, err := js.GetJobs(filter)
	if err != nil {
		fmt.Printf("could not list jobs: %v\n", err)
	}
	for _, j := range existingJobs {
		fmt.Printf("found job: %s\n", j.GetID())
		fmt.Printf("job state: %s\n", j.GetState().String())
	}

	jt := drmaa2interface.JobTemplate{
		RemoteCommand: "sleep",
		JobCategory:   "busybox:latest",
		Args:          []string{"360"},
	}

	_, err = js.RunJob(jt)
	if err != nil {
		panic(err)
	}
}
```

**Comment by Terf** [comment]
Thanks- your code works for me with docker, but when I use the libdrmaa backend the `existingJobs` array is always empty even though it doesn't appear to error (`err == nil`)?

**Comment by dgruber** [comment]
Interesting @Terf  Which HPC workload manager are you using with _libdrmaa_?

One of the reasons why DRMAA2 has been created was actually having a better job session management. Now since _libdrmaa.so_ is DRMAA1 some features are missing. Nevertheless, I realize that _drmaa2os_ does not exploit the contact string defined for DRMAA1 Init(). Actually the meaning of the contact string is implementation specific (so SLURM could be different to Grid Engine). 

If you follow the Grid Engine path the semantic is defined here:

https://gridengine.eu/mangridengine/htmlman3/drmaa_session.html

      "Contact  is  an  implementation
       dependent string which may be used to specify which Univa  Grid  Engine
       cell  to  use.  If  contact is NULL, the default Univa Grid Engine cell
       will be used. In the 1.0 implementation contact may have the  following
       value:   session=<session_id>.    To   determine  the  session_id,  the
       drmaa_get_contact(3) function should be called after  the  session  has
       already  been  initialized.  By passing the session=<session_id> string
       to the drmaa_init() function, instead of creating a new session,  DRMAA
       will  attempt  to reconnect to the session indicated by the session_id.
       The result of reconnecting to a previous session is that all jobs  pre-
       viously submitted in that session that are still running will be avail-
       able in the DRMAA session.  Note, however, that jobs which ended before
       the call to drmaa_init() may not be available or may have no associated
       exit information or resource usage data."

So, finished jobs are always lost (since the session string for DRMAA1 is not persistent, unlike DRMAA2 which is only available in the commercial version), but it could be achieved to re-connect to running jobs by persisting the session ID in the DB.

Here is the Go wrapper for DRMAA1:

    (s *Session) Init(contactString string)

https://github.com/dgruber/drmaa/blob/8cf613eb6f5f1a5cb1fba7f3703a787e92065409/drmaa.go

Wondering what the defined behavior of your workload manager is.

**Comment by Terf** [comment]
Thanks for your quick reply @dgruber, this really is an awesome project and I'm excited to see it integrated into the project I'm working on, [Penn's Image Processing Portal](https://ipp.cbica.upenn.edu). 

My cluster uses SGE 8.1.9, but for testing I used the SGE you setup in [this container](https://github.com/dgruber/drmaa2os/blob/master/examples/libdrmaa/Dockerfile). However my cluster admin says we're likely to migrate to SLURM as SGE has not been under recent development (part of the motivation to abstract it with DRMAA).

When I call `drmaa_get_contact` I indeed get a session ID back! So it seems this should be not terribly complicated to implement / something I could even figure out. For storing the ID in the database, do you think a new table should be created? I almost think it'd be most convenient to embed the session ID in the filename of the database since each session database should correspond to a session ID, but that seems hacky.

**Comment by dgruber** [comment]
You work on a great project @Terf 

There are a few things required to get it working as intended. 

    func (js *JobSession) GetContact() (string, error)

Needs to be implemented for the case the backend has some means for a contact string. 
Hence the jobtracker requires an optional function for returning the contract string, ideally
by new interface (_GetContactStringer_) so that it gets only called on job tackers which
have that function.

Additionally the contact string should also be stored. That's already implemented but there needs
to be a way to transparently query the contact string after the job session was created.
The open job session call requires to read to storage contact string and use that as parameter
for the job tracker.

Finally there is no job list function in DRMAA1 but we have that function here. Currently the drmaa1
job tracker stores jobs only in memory. There need to be a new storage which stores the job
IDs persistently. As there is already a bolt storage that can be used for jobs as well.

Sounds like great and useful enhancement. I will work on that...

**Comment by dgruber** [comment]
Can you please check branch issue_24 to see if it is working for you @Terf ?

I put an example with Son of Grid Engine (SoGE) in the examples/libdrmaasessions folder.

Basically there is now a new way of allocating a DRMAA1 session manager:

````
	params := libdrmaa.LibDRMAASessionParams{
		ContactString:           "",
		UsePersistentJobStorage: true,
		DBFilePath:              "testdbjobs.db",
	}
	sm, err := drmaa2os.NewLibDRMAASessionManagerWithParams(params, "testdb.db")
	if err != nil {
		panic(err)
	}
````

ContactString should be empty so that DRMAA is creating a new job session. This job session is stored in the SessionManager's DB (testdb.db) after the session is created, so it is going to be used transparently in the OpenSession call.  Nevertheless with old drmaa you can't list the jobs so job ids needs to be made persistent (in memory per default) which can be triggered by _UsePersistentJobStorage_ and giving yet another DB file path (must be different to session managers).

So when Create fails (as session already exists in DB) it tries to open the session. When jobs are finished in the DRMAA1 session they are not accessible anymore for now but running jobs are. Basic stuff can be executed (basically everything from the Job object which calls the jobtracker should work), like suspend, resume, terminate.

As there is now a persistence layer for job ids, this could be used for processes as well...similar things here finished processes are gone (and should be reaped from the process table after a proper wait call).

**Comment by Terf** [comment]
Amazing work @dgruber, thank you! I tested the example on my cluster and it worked perfectly, I'm very glad to be able to use this.

**Comment by dgruber** [comment]
@Terf You are welcome. The enhancement is now in the v0.3.13 release which finally will find its way into _wfl_ as way.

If you have more suggestions or have some enhancements please check them in. Closing the issue now.
